/*
 Navicat Premium Data Transfer

 Source Server         : LOCAL
 Source Server Type    : MySQL
 Source Server Version : 50724
 Source Host           : 127.0.0.1:3306
 Source Schema         : wpu_blog

 Target Server Type    : MySQL
 Target Server Version : 50724
 File Encoding         : 65001

 Date: 23/08/2022 03:55:46
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for categories
-- ----------------------------
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp(0) NULL DEFAULT NULL,
  `updated_at` timestamp(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `categories_name_unique`(`name`) USING BTREE,
  UNIQUE INDEX `categories_slug_unique`(`slug`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of categories
-- ----------------------------
INSERT INTO `categories` VALUES (1, 'Web Programming', 'web-programming', '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `categories` VALUES (2, 'Web Design', 'web-design', '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `categories` VALUES (3, 'Personal', 'personal', '2022-08-14 20:40:11', '2022-08-14 20:40:11');

-- ----------------------------
-- Table structure for failed_jobs
-- ----------------------------
DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE `failed_jobs`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `failed_jobs_uuid_unique`(`uuid`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for migrations
-- ----------------------------
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of migrations
-- ----------------------------
INSERT INTO `migrations` VALUES (1, '2014_10_12_000000_create_users_table', 1);
INSERT INTO `migrations` VALUES (2, '2014_10_12_100000_create_password_resets_table', 1);
INSERT INTO `migrations` VALUES (3, '2019_08_19_000000_create_failed_jobs_table', 1);
INSERT INTO `migrations` VALUES (4, '2019_12_14_000001_create_personal_access_tokens_table', 1);
INSERT INTO `migrations` VALUES (5, '2022_06_16_143837_create_posts_table', 1);
INSERT INTO `migrations` VALUES (6, '2022_06_19_231040_create_categories_table', 1);

-- ----------------------------
-- Table structure for password_resets
-- ----------------------------
DROP TABLE IF EXISTS `password_resets`;
CREATE TABLE `password_resets`  (
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp(0) NULL DEFAULT NULL,
  INDEX `password_resets_email_index`(`email`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for personal_access_tokens
-- ----------------------------
DROP TABLE IF EXISTS `personal_access_tokens`;
CREATE TABLE `personal_access_tokens`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `last_used_at` timestamp(0) NULL DEFAULT NULL,
  `created_at` timestamp(0) NULL DEFAULT NULL,
  `updated_at` timestamp(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `personal_access_tokens_token_unique`(`token`) USING BTREE,
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index`(`tokenable_type`, `tokenable_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for posts
-- ----------------------------
DROP TABLE IF EXISTS `posts`;
CREATE TABLE `posts`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `excerpt` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_at` timestamp(0) NULL DEFAULT NULL,
  `created_at` timestamp(0) NULL DEFAULT NULL,
  `updated_at` timestamp(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `posts_slug_unique`(`slug`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 24 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of posts
-- ----------------------------
INSERT INTO `posts` VALUES (1, 3, 2, 'Eveniet rem perspiciatis.', 'quod-excepturi-reiciendis-odit-est-itaque-et-et', NULL, 'Est tenetur accusantium quia voluptatem vel. Iste odio pariatur nihil qui non sunt molestiae. Modi facilis aut esse vel nemo iusto. Qui ea vel quia delectus aut ratione ad voluptas.', '<p>Cum alias minima perspiciatis est saepe. Eum ut ut officia ut. Id nobis nihil aliquid veniam. Nostrum odit qui consequatur dolor voluptatum ipsa enim quos.</p><p>Vitae laudantium a est et rem et. Facilis ea aut at. Omnis laborum placeat est atque quasi voluptas.</p><p>Quaerat qui sed quos sed. Accusamus assumenda totam id voluptatem. Quia qui sit nihil eveniet enim dolorem provident enim. Labore omnis enim reiciendis.</p><p>Sed voluptatibus quidem laudantium totam dolore. Tempora est explicabo autem delectus culpa quo eveniet cupiditate. Labore in rem voluptatibus vitae quas accusamus quia. Et ea ut sunt dolore.</p><p>Consequatur in dolorem officiis doloribus dolores maiores minus. Voluptatem sit molestias aliquam vel. Incidunt quia eum nihil. Vero hic quibusdam cumque vel magnam.</p><p>Enim fuga adipisci quisquam autem autem voluptatem sed. Sequi laborum quis rerum et sint. Sed dolorum laboriosam commodi qui et exercitationem tenetur. Ea nihil enim et nihil quisquam ab eos earum.</p><p>Vero voluptatem culpa voluptatem quia. Blanditiis error consectetur dolorem nihil id at quas. Delectus ducimus fugit vel et nihil ut ea.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (2, 3, 3, 'Omnis omnis rerum.', 'recusandae-sed-eum-quos-eveniet', NULL, 'Aut eveniet sit sed omnis assumenda consequuntur. Unde fugit qui at veritatis. Ratione ut odit natus dolorem. Dolorem unde mollitia similique ea.', '<p>Deserunt modi sint placeat velit. A error exercitationem quo maxime quidem possimus. Qui ab accusantium ut assumenda.</p><p>Blanditiis voluptas beatae sit qui. Voluptatem id necessitatibus et voluptate. Ut impedit velit nobis error fugit sed et. Aut magni in aperiam temporibus ut.</p><p>Modi iste ut enim fuga. Nulla alias magni perferendis rerum quia sit aspernatur. Aut voluptas dolor voluptatem occaecati dignissimos.</p><p>Aut atque est nisi placeat qui rerum. Sint asperiores est eius culpa repellendus. Eveniet impedit unde consequatur. Illo ut pariatur tenetur iste tempora ullam et.</p><p>Tempore distinctio omnis eveniet animi qui. Architecto nam nisi ratione possimus temporibus dolorem vitae et. Voluptates placeat placeat illum labore quo esse quos. Inventore qui nobis a corporis doloremque consequuntur error.</p><p>Ab alias expedita architecto. Eum possimus voluptatem velit ipsa ex. Illum sapiente sit nihil. Officiis deserunt quidem hic maiores officia quas. Sit molestias numquam optio numquam qui sit voluptatibus.</p><p>Eos neque qui non ipsa nihil. Amet cupiditate sequi aspernatur nemo. Quas exercitationem perferendis fuga qui ea sit illo.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (3, 3, 5, 'Laboriosam minus molestiae dicta nihil maxime et.', 'accusamus-eaque-recusandae-veniam-magni', NULL, 'Commodi ullam pariatur velit voluptatem. Tempore sed in atque earum quidem voluptatibus et. Debitis est illo quia amet vero incidunt. Nesciunt sequi quas quis consectetur.', '<p>Sunt aut est repellat soluta amet. Dolorem harum saepe excepturi qui dolorem et eum. Ut architecto eum porro temporibus quisquam quo.</p><p>Est maiores quas reprehenderit ea. Error consectetur ut et facere. Enim vitae doloremque dolores dolorem odit. Est necessitatibus sapiente iste quidem sit quod quia.</p><p>Possimus consequatur nobis neque asperiores culpa quaerat aut. Odit enim molestias excepturi labore illo. In aut reiciendis et sed. Consequatur placeat et aut facere qui est ipsum.</p><p>Veniam et nulla rerum facilis. Vitae totam sint quis explicabo nisi quasi. Quia voluptatum eligendi iure animi fuga.</p><p>Eaque quos id ea ducimus tempora quam consequatur. Nisi esse eos debitis in aut aspernatur corrupti cumque. Animi beatae iste velit et enim. Qui et ex voluptatum commodi consequatur rerum quasi.</p><p>Placeat qui ut id adipisci consequatur. Rerum est quia vero magnam suscipit rerum. Quae nisi ex laboriosam ut.</p><p>Reiciendis aut mollitia quia aspernatur in. Dolore adipisci eos consequatur temporibus a tempore quo. Quasi quidem possimus omnis fugiat porro ut. Enim consequatur vero consectetur sit. Dolorum numquam dolores incidunt at sunt minus.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (4, 3, 3, 'Veniam nisi assumenda ducimus magnam et.', 'ab-quia-ullam-et-expedita', NULL, 'Sit voluptatem est eaque quidem. Quam minima dolor aut qui est quaerat quidem. Debitis ullam repellat non dolorem. Quis harum odit et sunt repellat qui.', '<p>Voluptatum quia quasi ut voluptatum molestias. Quas velit eaque ab sunt quia dolor. Voluptatibus animi impedit corrupti omnis doloribus sint.</p><p>Omnis et ducimus itaque. Consequatur laudantium non rem aut deserunt voluptas a. Sapiente dolores dolores fuga. Doloremque consequatur possimus alias consequuntur. Qui dolore magnam hic ex dolor explicabo illum.</p><p>Velit id non adipisci et. Magni iure dicta voluptas mollitia quos quos minima. Velit perferendis qui aliquam et. Laborum omnis aut deleniti eaque vero.</p><p>Cum soluta voluptatibus odit consectetur. Et velit consequatur reiciendis dolores blanditiis quo consequatur. In repellendus fugit quo culpa quis ea libero. Velit et provident dolor ullam magni beatae.</p><p>Cum sed odio quia exercitationem dolor. Et omnis amet sit nisi praesentium sit. Voluptatum sint deserunt animi. Quis esse doloribus et minima quasi.</p><p>Perspiciatis qui voluptates harum architecto. Amet possimus nemo explicabo est unde quas. Et sed dolorem aliquam in eius quo reprehenderit.</p><p>Tenetur dolorum rerum aliquam vitae sed velit soluta. Deserunt architecto doloribus itaque placeat. Sed sit veritatis aliquid aliquam ut labore dignissimos et. Enim magni quis est quia atque et.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (5, 3, 4, 'Ducimus doloremque natus eum consequuntur error quas.', 'occaecati-id-quisquam-explicabo-est-aliquid-cupiditate', NULL, 'Occaecati vel harum vero nobis a voluptatibus. Sit dolorum sunt et omnis voluptatem facilis in. Aut aliquid voluptas ullam numquam. Eveniet officia deserunt voluptatum id.', '<p>Itaque libero consequatur sit non quibusdam saepe. Asperiores atque consequatur doloribus et optio beatae consectetur. Accusamus cumque necessitatibus sit facilis. Voluptate eligendi expedita assumenda rerum laudantium mollitia rem.</p><p>Odit expedita voluptate maiores voluptas. Eius at sit laboriosam aut aliquid molestiae quis. Corrupti suscipit quia eum vel quia. Autem iusto explicabo dolorem similique.</p><p>Eos nemo est soluta deleniti doloremque qui minus. At veritatis eveniet dolor aut facere et. In non sint culpa voluptatem asperiores sit facere. Sint voluptatem omnis numquam quo dolorem quos nihil.</p><p>Autem ad facilis et id quia ut. Tenetur aspernatur quasi corrupti voluptatibus corrupti. Provident at eos nemo. Neque voluptates et quia quia vel voluptatem sunt.</p><p>Voluptatem odit et aut tempora voluptas eligendi omnis. Velit perspiciatis voluptas unde aut autem. Eum vel aut ut dolorum quo. Non dolorem ut totam labore aspernatur qui qui est.</p><p>Autem occaecati et eos nobis numquam at. Id delectus laboriosam laborum voluptatibus et doloremque fugit. Earum reprehenderit quam sunt. Deserunt dignissimos vero ad dolorem earum corporis voluptates.</p><p>Quia et rerum qui totam ut. Molestiae nesciunt veniam dolorem excepturi id non omnis. Accusamus voluptas et tenetur ut est id.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (6, 3, 5, 'Est molestiae voluptatum.', 'non-quis-tempora-suscipit-est-dignissimos-asperiores', NULL, 'Modi laborum sapiente rerum quidem. Alias unde laboriosam magni nulla magnam rem fugiat sit. Incidunt animi ut non cupiditate. Et quasi alias asperiores.', '<p>Corporis eligendi soluta iste quia unde placeat autem. Voluptatem eveniet magni fuga laboriosam. Aut atque omnis cum qui deleniti.</p><p>Aut est provident ut dicta. Omnis est aut aut beatae. Et quia aut laudantium sunt. A et sit et repellendus eum. Nihil consequatur quaerat aut sit quasi consequuntur autem.</p><p>Dignissimos odio dicta rerum id quisquam asperiores. Nihil excepturi totam architecto voluptas sed. Quos quia magni ut ad aut commodi. Veniam repellat repellendus ipsum autem autem qui ducimus.</p><p>Dolor sequi deserunt aut nostrum aut eligendi inventore quaerat. Rerum dolorem eveniet est voluptatem. Quia vitae sapiente cumque. Qui earum quis expedita eum maxime quos non. Accusamus sunt reiciendis quaerat nostrum est aspernatur.</p><p>Aliquid molestiae nostrum ex totam modi. Quidem voluptates doloribus est esse aut delectus provident. Voluptatem voluptas dolores blanditiis est accusantium odio. Voluptates quos mollitia vel non.</p><p>Et provident autem consectetur. Veritatis ducimus veniam sunt dolores commodi beatae aperiam aliquam. Quia doloribus sunt culpa praesentium delectus. Dolorum dolores voluptatem consequuntur odio tempora.</p><p>Maiores esse vero inventore omnis recusandae et minima. Harum atque vero facilis et quia sint. Omnis molestias autem autem totam accusamus omnis sint et.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (7, 3, 5, 'Doloribus rem a minima.', 'aut-nam-eaque-odio-voluptatibus-harum-qui', NULL, 'Velit quis minima perferendis tempora aut animi. Rerum optio voluptatem recusandae ut voluptas dolores. Sit ab ratione sint temporibus rerum illo. Ut recusandae ab ut corrupti velit.', '<p>Quis accusamus neque voluptas enim cumque voluptas delectus eaque. Aliquid cum voluptatum veniam sed. Et maxime voluptatibus assumenda eos voluptas quasi qui. Sed tenetur dolorem aut esse in eaque.</p><p>Unde numquam sit quisquam est ratione corrupti deleniti eaque. Animi et provident voluptates quia enim voluptates. Explicabo consequuntur dolorem et deserunt maiores. Ut accusantium et rem totam omnis corporis sunt quas.</p><p>Nemo porro qui ipsa blanditiis voluptas modi. Ut consequuntur dolorem unde. Dolorem et beatae quis aut sed.</p><p>Et id doloremque vel et. Ut voluptatem sunt deserunt porro eos aliquam laboriosam et. Qui tempora quia repudiandae maxime beatae a dolores sint. Corporis quibusdam enim a.</p><p>Occaecati rerum accusamus fugiat voluptas. Quam corporis facere quia ea. Velit et molestiae repudiandae doloremque consequatur rerum ut.</p><p>Accusamus expedita sit a voluptatem nisi quasi est. Dolores facere quibusdam veniam nostrum minima dolores. Minus nihil dolores temporibus perferendis.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (8, 3, 4, 'Numquam voluptate illum.', 'consequuntur-rerum-aliquid-recusandae-facilis-est-et', NULL, 'Et iusto eum perspiciatis aut esse laboriosam ea. Quia qui cumque sit aliquid corporis. Ea commodi excepturi nostrum quis illum mollitia.', '<p>Vitae ratione fuga consequatur voluptatem tempore aut. Iusto tempora eligendi fuga voluptate voluptate eos exercitationem.</p><p>Dolorum natus quae quo incidunt vel. In cum nulla ipsam ut blanditiis a incidunt. Possimus ratione rem omnis.</p><p>Earum repudiandae ut animi minus quidem et et. Voluptate minus sunt rerum magnam reprehenderit perferendis sed sint. Neque aut ullam assumenda sed. Quo et repudiandae quaerat sequi delectus.</p><p>Cumque excepturi laudantium voluptatem reiciendis dolor omnis sapiente. Qui optio doloremque voluptatum est id ab. Voluptatibus et et laborum aut.</p><p>Nam iusto et fugiat amet. Aut est dolores vel modi nisi aperiam. Eum excepturi nihil ea quo quam.</p><p>Maiores natus et odit vel veritatis. Nihil illo placeat neque voluptatum.</p><p>Deleniti deserunt omnis perferendis eum neque. Id doloremque nam rerum consequatur assumenda hic iure rem. Autem et quis optio at numquam aperiam. Voluptatum quia in laboriosam numquam enim similique.</p><p>Earum provident neque vel quis. Enim porro quia quis eum quas autem ipsam. Quo corporis iste corrupti sed esse. Perspiciatis sunt corrupti minima.</p><p>Dolore molestiae et aut ut quia culpa. Sint quae maiores quia rerum. Velit aspernatur voluptates qui ipsam sit autem rerum omnis. In consequatur impedit sapiente.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (10, 3, 3, 'Distinctio molestiae magnam et porro eius.', 'in-odit-sit-deserunt-earum-ab-aliquam', NULL, 'Blanditiis et rerum praesentium vel deserunt rem. Quas qui dolores delectus fuga numquam quibusdam recusandae. Et ullam id et voluptas consequatur et voluptate et.', '<p>Neque at quisquam veniam. Ut non impedit sed ut. Praesentium ea sit voluptatem consequatur ab. Dignissimos repellat alias et illum sed sed.</p><p>Ratione dolorem aspernatur incidunt tempore similique sed. Soluta repellat quos aliquid sint quasi ut sit. Assumenda excepturi voluptates maxime et illum.</p><p>Est sint qui autem fuga ea ut eius itaque. Asperiores possimus sunt repellat enim consequatur qui rem. Itaque placeat ut et voluptatem.</p><p>Eum dignissimos esse et inventore. Sit porro autem culpa iste rerum. Occaecati iste in totam vel dolor temporibus.</p><p>Sapiente adipisci quo reprehenderit velit nihil hic. A qui nihil est vero earum ipsam atque id. Et recusandae ratione voluptas sunt. Et sunt eaque et nihil placeat.</p><p>Nobis et doloremque omnis asperiores molestias reiciendis officia. Sed aut officiis sed omnis. Aut numquam reiciendis accusantium nihil.</p><p>Atque est doloremque quibusdam voluptatem. Labore quibusdam rerum blanditiis. Vitae ad accusantium et.</p><p>Maxime et exercitationem voluptatem harum voluptate eius eius qui. Assumenda ea consequuntur veniam quo. Ea alias deleniti quia perspiciatis quam.</p><p>Repudiandae fuga dicta ea. Magni est voluptas dolorem possimus modi ut sed. Id deleniti eos omnis rerum voluptatum quas dolores. Sed pariatur qui eligendi ipsa consequuntur.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (11, 3, 4, 'Aspernatur iusto iste perferendis quaerat vel.', 'maxime-aut-consequatur-dolore-praesentium-fugit-maxime-eos', NULL, 'Velit adipisci aliquam et nobis. Ut in sit voluptatem aliquam voluptas blanditiis. Sunt earum quaerat mollitia omnis reiciendis eos. Dolor soluta sit dolorum et odit rerum aperiam iure.', '<p>Fuga praesentium in velit porro quibusdam. Eum nihil fugiat quisquam blanditiis sit fugit ipsam tempora. Pariatur tempora sed consequuntur maiores aut fugit.</p><p>Voluptatem laudantium incidunt explicabo natus aut voluptate officia quam. Voluptas aspernatur at dignissimos atque nulla est. Corporis enim enim cupiditate ut magni.</p><p>Alias voluptatem facere et voluptatem molestiae minus rerum. Consequatur voluptatem suscipit non rerum. Sint voluptatem architecto reprehenderit dolores ullam commodi.</p><p>Perspiciatis unde molestias consequatur nemo tempore vel quisquam. Voluptas hic consequuntur aut. Harum doloremque aperiam sint laboriosam omnis voluptas.</p><p>Rem corrupti dolores excepturi sit voluptas quia distinctio. Aut asperiores rerum doloremque error nemo odio natus. Et tempore voluptas praesentium et laudantium quibusdam. Ducimus velit doloremque magni ut beatae sapiente fugiat distinctio. Est excepturi eos eum tempora accusamus.</p><p>Qui earum commodi est nihil magni odio. Architecto eius dolores adipisci.</p><p>Dolorem rerum totam impedit et vel dignissimos. Dolores repellat ab possimus corrupti. Expedita et illo nihil minima incidunt.</p><p>In commodi architecto quam. Omnis tempore ut natus. Recusandae quia numquam non.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (12, 3, 2, 'Aut ducimus et.', 'doloremque-odit-voluptas-ut-non-quis', NULL, 'Omnis et est error dolore facilis nihil repudiandae. Amet cum voluptatibus nobis quibusdam. Accusamus fuga necessitatibus ut deserunt accusamus.', '<p>Dolorem repellat in sit qui ullam aut iure. Velit earum voluptatem est consequatur dignissimos voluptatum alias ullam. Sunt nobis consequatur dolor eveniet.</p><p>Perferendis et accusantium id cupiditate eveniet. Rem facilis atque quos id sed ut temporibus. Ab animi incidunt in et. Et rerum provident culpa consequatur.</p><p>Corrupti et impedit temporibus qui cupiditate. Harum nemo quibusdam et nostrum. Qui exercitationem dignissimos facere et voluptatum.</p><p>Vel rerum dolore dolore vel animi quis voluptatem. Expedita harum reiciendis sint fuga sint aliquid.</p><p>In at temporibus dolores dolorem est impedit dolores. Quisquam voluptas et animi aut voluptas id mollitia. Libero voluptatum ipsa animi facere.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (13, 3, 4, 'Quam voluptatem dolorum illo.', 'tenetur-numquam-beatae-sint-laudantium-consequuntur-porro-porro-ab', NULL, 'Distinctio qui praesentium tempora consequatur modi eveniet est. Quos dolor minus molestiae aperiam laboriosam et delectus architecto. Dolorem qui harum libero. Quas ut saepe deleniti harum. Cupiditate atque id sed.', '<p>Et voluptas quam voluptatem pariatur omnis consectetur explicabo. Iusto in et quaerat voluptatibus. Alias omnis quis aut porro amet. Nihil voluptatem enim maxime et velit voluptates dolores.</p><p>Ducimus veniam voluptatem quibusdam voluptatem nesciunt aut. Dicta sequi autem sed assumenda sed quas et. Dicta sed delectus sapiente temporibus. Assumenda quidem necessitatibus amet excepturi quia non.</p><p>Similique corporis voluptas nulla aut et qui nam. Nulla officiis minima atque expedita quisquam. Reiciendis eius necessitatibus excepturi aut ut sequi repudiandae.</p><p>In aliquam accusantium voluptates dolorem. Deserunt ea rerum recusandae consectetur occaecati et. Nisi reprehenderit autem et cum eligendi. Sint qui illum fuga quis labore sunt.</p><p>Et debitis iusto maiores voluptatibus vero est. Tempora accusantium nostrum qui ex ipsam voluptates ipsam. In velit asperiores voluptate praesentium labore nobis soluta. Delectus omnis totam aperiam officia veritatis temporibus dolores ipsum. Nihil ex tempore non magni quaerat et debitis dignissimos.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (14, 3, 5, 'Soluta ullam alias in dicta velit cupiditate.', 'molestiae-eum-ut-laboriosam-dignissimos-necessitatibus', NULL, 'Harum dolores libero assumenda natus dolores. Illo laboriosam facilis consequatur modi.', '<p>Esse voluptatem velit sint similique autem magnam ab. Explicabo adipisci quia nostrum ut velit velit.</p><p>Doloribus commodi ullam nesciunt ipsum. Ipsum reiciendis distinctio iure. Sequi neque ut soluta distinctio aspernatur animi neque.</p><p>Sit voluptatibus aliquid voluptas repudiandae ratione sint et. Laboriosam deserunt enim asperiores dolor sit sapiente. Quibusdam corrupti rerum culpa nobis asperiores itaque.</p><p>Dignissimos dolores distinctio et unde ut assumenda. Ipsum necessitatibus corporis exercitationem minus quaerat culpa placeat.</p><p>Molestias rem non officia quaerat cumque sed quis. Nostrum minima tempora itaque iste doloremque non quasi voluptatem. Omnis velit eum iure veniam sunt magnam.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (15, 3, 5, 'Minima quae eligendi itaque saepe iure.', 'eum-aliquid-qui-rerum-quos-sit', NULL, 'Vel explicabo consequuntur sequi velit est et laudantium. Enim soluta asperiores ex non nihil deleniti facilis labore. Voluptatum est libero ut fuga velit. Et qui culpa non nulla ad est velit. Ducimus enim deleniti voluptatem porro accusantium architecto vel.', '<p>Sapiente debitis necessitatibus illum. Rem magnam aut dolorum facilis. Minus vel placeat consectetur recusandae sapiente odit. Sit accusantium itaque autem.</p><p>Ad amet earum ullam reiciendis quae exercitationem sint. Modi voluptatem asperiores impedit voluptatem. Totam omnis dicta laudantium sunt velit.</p><p>Deleniti enim in voluptatem ad quam dolor. Quae animi deleniti reprehenderit est eos voluptate. Tempore adipisci nobis laudantium consequuntur eligendi necessitatibus.</p><p>Praesentium molestias placeat adipisci ullam quas aut. Fuga at molestias qui hic nisi sapiente maxime. Dolores dicta rerum quos maiores fugiat libero.</p><p>Iusto et et aut libero dolore voluptatem. Distinctio maxime esse porro. Cum velit ut quo.</p><p>Eos a esse vero aspernatur quod cum. Dolores ab voluptate officiis aut odio. Dolores nam neque occaecati.</p><p>Voluptas nulla dolores iusto quidem velit modi voluptatum sint. Quas expedita sunt est nisi. Nam maxime quibusdam sit dolor accusantium facere.</p><p>Fugit exercitationem optio vero. Qui non ut sit iure asperiores. Velit aut dicta maiores.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (16, 3, 3, 'Illum illo nesciunt qui ut quae illo enim.', 'nisi-praesentium-accusamus-placeat-voluptate-ipsam', NULL, 'Enim id natus aliquid aliquam. Sit et id autem officiis modi aliquam. A accusamus et est consequatur mollitia.', '<p>Tempora adipisci dolore dolor omnis suscipit cum. Quidem quaerat et illum cupiditate eligendi adipisci aut. Accusantium accusamus voluptatum vel modi officia unde. Inventore ut recusandae ut molestiae.</p><p>Possimus necessitatibus ut omnis et. Impedit provident et dolores voluptatem in quia. Incidunt reiciendis quia rerum.</p><p>Excepturi qui at dolor iure. Voluptates vel quas sunt nemo aspernatur reiciendis. Magni quae non eos autem eos. Aut unde vitae impedit rerum qui.</p><p>Debitis sequi minus dolores molestias asperiores dolorem nam. Deserunt itaque eveniet voluptas provident quae animi. A earum consequatur dolorum nam ducimus accusamus nihil.</p><p>Aut odit consequatur ab. Ullam eos enim eum excepturi aut quae placeat. Vitae velit omnis delectus ipsum asperiores quasi. Atque id et accusantium necessitatibus culpa eligendi cum.</p><p>Est at ut ipsa ex corrupti. Nobis sunt natus voluptates libero non autem et. Et accusantium vel et nisi maiores.</p><p>Facere necessitatibus voluptate dolorem velit et possimus. Ut corporis rerum quam alias maxime exercitationem laudantium excepturi. Illum qui adipisci et qui sunt sapiente veritatis reiciendis.</p><p>Harum iure doloribus sed ipsum alias a ut. Sit aspernatur delectus tempore molestiae fuga commodi. Cum quia suscipit rerum molestiae libero. Numquam quos ut fugit nisi hic.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (17, 3, 4, 'Rerum voluptas minus.', 'ut-deserunt-reprehenderit-sed-rerum-quis-ab', NULL, 'Odio minima qui blanditiis non ipsum veritatis. Qui illum porro perspiciatis natus quam sint. Ea tenetur fugiat animi quisquam enim nihil asperiores tempore. Ut quod adipisci sed sequi dolor praesentium.', '<p>Quod culpa a vero doloribus. Quasi est quasi velit iste dolores. Aperiam in ut explicabo nobis incidunt facilis.</p><p>Eum eos vel enim aliquid ullam. Repellendus qui facere voluptatum consequuntur sint quis. Vel nihil qui voluptate in ea sit.</p><p>Delectus ut fugiat quidem. Eveniet eum aut assumenda. Saepe et quisquam exercitationem ipsum at labore nisi cupiditate.</p><p>Occaecati nesciunt ex enim eos eaque perferendis a nihil. Qui voluptates et ut voluptatem temporibus sit et odit. Aut qui officia et ut et facere recusandae. Sit qui necessitatibus aut laudantium eaque. Qui maiores quo et dignissimos placeat occaecati.</p><p>Nihil qui ab debitis ea. Et perferendis nam aut rerum. Eius et maxime voluptatem vitae delectus vitae laudantium. Ut ea rerum optio rerum voluptas quia et.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (18, 3, 4, 'Ad assumenda mollitia.', 'dolore-id-id-voluptatem-neque-aliquam-sunt-quasi', NULL, 'Velit voluptas deleniti aut ad et labore. Cum doloremque expedita laboriosam qui numquam. Animi minus et ut voluptas consequatur non.', '<p>Laboriosam alias qui est odio sapiente harum officia. Distinctio maiores eos explicabo voluptatem minima nobis reprehenderit. Occaecati est similique aliquid enim et laborum. Quia qui incidunt nam eum. Delectus qui est soluta voluptate animi.</p><p>Beatae ducimus soluta nulla exercitationem ex enim illum id. Repellat vel ullam reiciendis ad. Facilis consequuntur neque laboriosam incidunt autem facilis ut.</p><p>Maiores reiciendis nesciunt cum eaque similique. Repellendus doloremque recusandae vitae omnis libero. Earum sint recusandae officiis eum occaecati quia porro. Qui commodi omnis vero.</p><p>Sed sunt officiis molestiae reiciendis. Ducimus rerum ut nobis ullam. Fugit quia eligendi laudantium quia earum.</p><p>Est quisquam placeat sint provident alias. Officiis eligendi qui quia.</p><p>Rerum sunt est unde numquam iure omnis aliquam. Laboriosam est fugit ut est. Maxime odit optio est quidem ducimus veritatis. Accusantium rerum ea iste et molestiae.</p><p>Et quis totam voluptates quaerat. Voluptatum dolore aliquam beatae sint consectetur eum. Molestiae hic sunt et qui molestiae consequatur.</p><p>Doloribus expedita sit corrupti ut soluta id. Perferendis et vitae sed deserunt hic corporis. Quia velit dolores voluptatem veritatis. Et aut officiis voluptatem itaque iste occaecati unde.</p><p>Omnis excepturi sequi eos rem aut a. Voluptatum tenetur a quis molestiae quasi. Quia voluptas fuga a unde. Sit earum cumque cupiditate omnis ex et eligendi.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (20, 3, 3, 'Eveniet sunt dicta.', 'eius-et-iusto-nulla', NULL, 'Nam aut voluptatum est temporibus repellendus. Quibusdam ipsum quia quas quibusdam. Ducimus blanditiis nemo eius harum quisquam. Veritatis ut quia ut sed tempore autem. Tempora praesentium voluptas iste consequatur vel voluptas.', '<p>Dolore tempore maiores quia possimus voluptas. Veritatis qui accusamus quas ab. Vel facere unde est ratione beatae quaerat.</p><p>Temporibus quisquam quae ipsa unde. Ex alias hic mollitia iure.</p><p>Repellendus placeat placeat tempore reprehenderit et qui. Suscipit praesentium sunt voluptas sit vero dolorem quod. Minima deserunt pariatur sint velit libero atque quia.</p><p>Et neque reprehenderit molestiae voluptatum necessitatibus consequatur. Voluptas sed reiciendis libero praesentium qui. Molestiae velit voluptatem ut occaecati.</p><p>Veniam commodi inventore totam deleniti aut. Sit placeat enim in possimus aut temporibus. Quidem nemo esse ut ab. Sed maxime vero voluptatem repudiandae.</p><p>Dignissimos consequuntur ducimus quod quidem iusto maxime et consequatur. Facilis aspernatur assumenda quos autem quas ad totam sit. Dolores in et molestiae impedit est a sed corporis.</p><p>Magni non veniam aperiam. Alias qui sequi et ipsum occaecati voluptatem dolorem. Autem sint sit adipisci magnam ut et. Ea mollitia voluptas perspiciatis occaecati. Maiores tempora voluptate velit natus suscipit consectetur.</p><p>Optio explicabo repellat optio labore nesciunt corrupti est. Similique consequatur amet ex qui nobis alias velit. Voluptas adipisci maiores beatae eos. Architecto et soluta ut repudiandae quia culpa voluptate.</p>', NULL, '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `posts` VALUES (21, 2, 1, 'Design Kuda', 'design-kuda', 'post-images/4KfzhRBZs2h9qaZXFlaWO33GS99Eual80KgivOPQ.jpg', '&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras cursus, urna sodales ornare fringilla, tellus tellus malesuada ante, eget sagittis...', '<div>&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras cursus, urna sodales ornare fringilla, tellus tellus malesuada ante, eget sagittis neque sem vitae erat. Praesent elementum cursus quam, vehicula interdum enim luctus vel. Praesent id facilisis metus. Nullam id vehicula odio. Aenean massa felis, dignissim ornare molestie et, dictum id magna. Duis lobortis venenatis fringilla. Nulla fermentum id lectus ut finibus. Pellentesque at volutpat risus. Sed fringilla, tellus rhoncus auctor consectetur, lacus felis laoreet purus, sit amet gravida nulla nulla sit amet dui. Pellentesque molestie sem nec dolor ornare pulvinar. Pellentesque eget molestie leo.&nbsp;<br><br></div><div>&nbsp;Proin ac urna rhoncus, molestie elit eget, pulvinar ipsum. Sed dictum, augue eget gravida consectetur, felis ex viverra eros, vel tempus diam est non nibh. Morbi at sodales odio, vitae interdum nulla. Sed pellentesque mauris nec massa ullamcorper ultrices. Nam at lacinia mauris. Fusce in tortor nisl. Maecenas mollis erat at ultricies auctor. Pellentesque lacus nulla, convallis sed lacinia eu, tristique euismod augue. Morbi consectetur auctor sodales. Aliquam erat volutpat.&nbsp;<br><br></div><div>&nbsp;Mauris bibendum rutrum volutpat. Nam tristique suscipit leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec condimentum nisi nulla, quis commodo dolor cursus non. Cras dictum mattis auctor. Sed at velit egestas, facilisis mi ut, congue est. Fusce consectetur augue at mi laoreet, non auctor metus laoreet.&nbsp;<br><br></div><div>&nbsp;Fusce venenatis pretium elementum. Cras ex nunc, tincidunt congue felis ac, vulputate condimentum tortor. Nullam porta, orci ut tristique scelerisque, elit ligula faucibus tellus, in vulputate metus elit sit amet sem. Nam vulputate, neque id imperdiet tempus, nibh sapien condimentum tellus, in convallis nibh risus ac turpis. Pellentesque a cursus neque, vitae consequat diam. Cras odio elit, facilisis ut nisl luctus, elementum commodo tortor. Nam nisi mauris, molestie non dui et, tincidunt porttitor ex. Pellentesque habitant morbi tristique senectus et netus et malesuada.&nbsp;<br><br></div>', NULL, '2022-08-14 20:57:41', '2022-08-23 03:39:06');
INSERT INTO `posts` VALUES (22, 2, 1, 'Peta Indonesia', 'peta-indonesia', 'post-images/TeoMB1Qz63Vz4aNB5Osny7Gf0RZGnAtk94d61EhX.jpg', '&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras cursus, urna sodales ornare fringilla, tellus tellus malesuada ante, eget sagittis...', '<div>&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras cursus, urna sodales ornare fringilla, tellus tellus malesuada ante, eget sagittis neque sem vitae erat. Praesent elementum cursus quam, vehicula interdum enim luctus vel. Praesent id facilisis metus. Nullam id vehicula odio. Aenean massa felis, dignissim ornare molestie et, dictum id magna. Duis lobortis venenatis fringilla. Nulla fermentum id lectus ut finibus. Pellentesque at volutpat risus. Sed fringilla, tellus rhoncus auctor consectetur, lacus felis laoreet purus, sit amet gravida nulla nulla sit amet dui. Pellentesque molestie sem nec dolor ornare pulvinar. Pellentesque eget molestie leo.&nbsp;<br><br></div><div>&nbsp;Proin ac urna rhoncus, molestie elit eget, pulvinar ipsum. Sed dictum, augue eget gravida consectetur, felis ex viverra eros, vel tempus diam est non nibh. Morbi at sodales odio, vitae interdum nulla. Sed pellentesque mauris nec massa ullamcorper ultrices. Nam at lacinia mauris. Fusce in tortor nisl. Maecenas mollis erat at ultricies auctor. Pellentesque lacus nulla, convallis sed lacinia eu, tristique euismod augue. Morbi consectetur auctor sodales. Aliquam erat volutpat.&nbsp;<br><br></div><div>&nbsp;Mauris bibendum rutrum volutpat. Nam tristique suscipit leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec condimentum nisi nulla, quis commodo dolor cursus non. Cras dictum mattis auctor. Sed at velit egestas, facilisis mi ut, congue est. Fusce consectetur augue at mi laoreet, non auctor metus laoreet.&nbsp;<br><br></div>', NULL, '2022-08-14 21:43:55', '2022-08-23 03:50:39');
INSERT INTO `posts` VALUES (23, 2, 1, 'Logo Tokopedia', 'logo-tokopedia', 'post-images/KioJKcHFLyfWubGE3ozalsqWqVicXGbtL9Wx2hHC.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras cursus, urna sodales ornare fringilla, tellus tellus malesuada ante, eget sagittis neque...', '<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras cursus, urna sodales ornare fringilla, tellus tellus malesuada ante, eget sagittis neque sem vitae erat. Praesent elementum cursus quam, vehicula interdum enim luctus vel. Praesent id facilisis metus. Nullam id vehicula odio. Aenean massa felis, dignissim ornare molestie et, dictum id magna. Duis lobortis venenatis fringilla. Nulla fermentum id lectus ut finibus. Pellentesque at volutpat risus. Sed fringilla, tellus rhoncus auctor consectetur, lacus felis laoreet purus, sit amet gravida nulla nulla sit amet dui. Pellentesque molestie sem nec dolor ornare pulvinar. Pellentesque eget molestie leo.&nbsp;<br><br></div><div>&nbsp;Proin ac urna rhoncus, molestie elit eget, pulvinar ipsum. Sed dictum, augue eget gravida consectetur, felis ex viverra eros, vel tempus diam est non nibh. Morbi at sodales odio, vitae interdum nulla. Sed pellentesque mauris nec massa ullamcorper ultrices. Nam at lacinia mauris. Fusce in tortor nisl. Maecenas mollis erat at ultricies auctor. Pellentesque lacus nulla, convallis sed lacinia eu, tristique euismod augue. Morbi consectetur auctor sodales. Aliquam erat volutpat.&nbsp;<br><br></div><div>&nbsp;Mauris bibendum rutrum volutpat. Nam tristique suscipit leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec condimentum nisi nulla, quis commodo dolor cursus non. Cras dictum mattis auctor. Sed at velit egestas, facilisis mi ut, congue est. Fusce consectetur augue at mi laoreet, non auctor metus laoreet.&nbsp;<br><br></div><div>&nbsp;Fusce venenatis pretium elementum. Cras ex nunc, tincidunt congue felis ac, vulputate condimentum tortor. Nullam porta, orci ut tristique scelerisque, elit ligula faucibus tellus, in vulputate metus elit sit amet sem. Nam vulputate, neque id imperdiet tempus, nibh sapien condimentum tellus, in convallis nibh risus ac turpis. Pellentesque a cursus neque, vitae consequat diam. Cras odio elit, facilisis ut nisl luctus, elementum commodo tortor. Nam nisi mauris, molestie non dui et, tincidunt porttitor ex. Pellentesque habitant morbi tristique senectus et netus et malesuada.&nbsp;<br><br></div>', NULL, '2022-08-14 22:43:42', '2022-08-23 03:53:22');

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `is_admin` tinyint(1) NOT NULL DEFAULT 0,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `created_at` timestamp(0) NULL DEFAULT NULL,
  `updated_at` timestamp(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `users_username_unique`(`username`) USING BTREE,
  UNIQUE INDEX `users_email_unique`(`email`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES (1, 'Amrun Hakim', 'amrun.hakim', 'amha.hakim@gmail.com', '2022-08-14 20:40:10', 0, '$2y$10$DJ3PJucQ4u.DZC62WPTohO/B.HiWKhEdp3hVXB2w2V0wHs5Po5wte', NULL, '2022-08-14 20:40:10', '2022-08-14 20:40:10');
INSERT INTO `users` VALUES (2, 'Catur Siregar', 'cakrawangsa47', 'jmegantara@example.org', '2022-08-14 20:40:11', 0, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'IVVtCGBDRh', '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `users` VALUES (3, 'Asmianto Narpati', 'winarno.eko', 'hwijayanti@example.net', '2022-08-14 20:40:11', 0, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'oz1llrAvcS', '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `users` VALUES (4, 'Ella Puspasari', 'raden.kusumo', 'leo95@example.com', '2022-08-14 20:40:11', 0, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'y70znwrcO1', '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `users` VALUES (5, 'Rendy Karman Utama', 'tedi.sihotang', 'iyolanda@example.net', '2022-08-14 20:40:11', 0, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '65d91SEyMo', '2022-08-14 20:40:11', '2022-08-14 20:40:11');
INSERT INTO `users` VALUES (6, 'Bambang Ibrahim Nainggolan', 'eka.iswahyudi', 'nasrullah.permata@example.org', '2022-08-14 20:40:11', 0, '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'HDBuxCMpD7', '2022-08-14 20:40:11', '2022-08-14 20:40:11');

SET FOREIGN_KEY_CHECKS = 1;
